### ISSUE TITLE
request COPR repo build enable for F35

### ISSUE THREAD

**Issue by pgnd** [adrienverge/copr-some-nice-fonts#1]
with F35 around the corner, could you enable repo builds @

https://copr.fedorainfracloud.org/coprs/adrienverge/some-nice-fonts/

for F35?

still the most convenient install method for MS' fonts!

thx!

**Comment by adrienverge** [comment]
Thanks for the ping, a new build for Fedora has just been created by @h--o-l. Glad you like this package!
