### ISSUE TITLE
 request COPR repo build enable for F36

### ISSUE THREAD

**Issue by pgnd** [adrienverge/copr-some-nice-fonts#2]
it's that time again :)

could you enable builds @ 

https://copr.fedorainfracloud.org/coprs/adrienverge/some-nice-fonts/

for F36?

thx!

**Comment by adrienverge** [comment]
Hello,

Here you go :)
https://copr.fedorainfracloud.org/coprs/adrienverge/some-nice-fonts/build/4395706/
